name: Fetch & Manipulate parkrun Data 
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */3 * * MON-THU'
  - cron: '0 0-15/3,18-23 * * FRI'
  - cron: '0 0-9,12/3 * * SAT'
  - cron: '30 5-9 * * SAT'
  - cron: '0 0,3-8,9/3 * * SUN'
  
jobs:
  parkrun_data:
    name: Fetch & Manipulate parkrun Data
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, '[Bot]') && !contains(github.event.head_commit.message, '[No Data Refresh]')}}
    steps:
        
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: requirements.txt

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script
      run: python parkrun_data.py
      # continue-on-error: true
    
    - name: Get Current Time
      uses: josStorer/get-current-time@v2.1.2
      id: current-time
    
    - name: Write Time to File
      run: |
        echo 'time' > _data/raw/time.tsv
        echo ${{ steps.current-time.outputs.time }} >> _data/raw/time.tsv

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add _data/
        git add _posts/'Cancellation Updates'
        if git diff --staged --quiet; then
          echo "No data changes to commit."
          exit 0
        fi
        git commit -m "Update parkrun Data [Bot]"

    - name: Push changes
      uses: ad-m/github-push-action@v1.1.0
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: ${{ github.ref }}
        

